[Main]

; Platform selection
PLATFORM = OpenCL

; Input data
LOOPS_PATH = /home/blackpianocat/Data/method_paper_data/ENCSR184YZV_CTCF_ChIAPET/LHG0052H_loops_cleaned_th10_2.bedpe
COMPARTMENT_PATH = /home/blackpianocat/Data/Trios/HiChIP/HiChIP_Subcompartments/calder_subc_50k/bed/HG00513_30.bed
LOC_START = 119222888
LOC_END =  159222888
CHROM = chr5
INITIAL_STRUCTURE_TYPE = hilbert
OUT_PATH = tmp/test

; Simulation Parameters
N_BEADS =2000
CPU_THREADS = 24
SHUFFLE_CHROMS = False
NUC_DO_INTERPOLATION = False

; Enable forcefield for genome-wide simulation
SC_USE_SPHERICAL_CONTAINER = False
CHB_USE_CHROMOSOMAL_BLOCKS = False
COB_USE_COMPARTMENT_BLOCKS = True
IBL_USE_B_LAMINA_INTERACTION = False
CF_USE_CENTRAL_FORCE = False
LE_LOOP_FORCE_TYPE = fene_soft
COB_FORCE_TYPE = theta
BLAMINA_FORCE_TYPE = logistic_shell

; Simulation Parameters
SIM_RUN_MD = True
SIM_SAMPLING_STEP = 50
SIM_N_STEPS = 20000
TRJ_FRAMES = 100
