[Main]

; Platform selection
PLATFORM = OpenCL

; Input data
LOOPS_PATH = /home/blackpianocat/Data/method_paper_data/ENCSR184YZV_CTCF_ChIAPET/LHG0052H_loops_cleaned_th10_2.bedpe
COMPARTMENT_PATH = /home/blackpianocat/Data/Trios/HiChIP/HiChIP_Subcompartments/calder_subc_50k/bed/HG00513_30.bed
LOC_START = 16000000
LOC_END = 17950000
CHROM = chr1
INITIAL_STRUCTURE_TYPE = rw
OUT_PATH = tmp/test
; SIMULATION_TYPE = REGION

; Simulation Parameters
N_BEADS = 2000
CPU_THREADS = 24
SHUFFLE_CHROMS = False
NUC_DO_INTERPOLATION = False

; Enable forcefield for genome-wide simulation
SC_USE_SPHERICAL_CONTAINER = False
CHB_USE_CHROMOSOMAL_BLOCKS = False
COB_USE_COMPARTMENT_BLOCKS = True
IBL_USE_B_LAMINA_INTERACTION = False
CF_USE_CENTRAL_FORCE = False
LE_LOOP_FORCE_TYPE = fene_soft
COB_FORCE_TYPE = theta
BLAMINA_FORCE_TYPE = logistic_shelli

; Ensemble creation
GENERATE_ENSEMBLE = True
COMPARTMENT_FLIP_PROB = 0.4
COMPARTMENT_NOISE_STD = 1.0
N_ENSEMBLE = 5
DOWNSAMPLING_PROB = 0.9

; Simulation Parameters
SIM_RUN_MD = True

SIM_SAMPLING_STEP = 50
SIM_N_STEPS = 10000
TRJ_FRAMES = 100
